---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  region: us-east-1
  availability_zone: us-east-1b
  security_group_ids:
    - ci-testing
  instance_type: c3.large
  iam_profile_name: test-kitchen
  interface: public
  tags:
    Env: dev
    Type: test

transport:
  name: sftp
  ssh_key: <%= ENV['EC2_SSH_KEY_PATH'] %>

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    driver:
      tags:
        Name: s3-put-default-ubuntu-1604
    run_list:
      - recipe[test_s3_put::default]
    attributes:
      test_s3_put:
        bucket: ops
        remote_path: chef/test_s3_put

  - name: default-chef12
    driver:
      tags:
        Name: s3-put-default-chef12-ubuntu-1604
    provisioner:
      product_name: chef
      product_version: 12
    run_list:
      - recipe[test_s3_put::default]
    attributes:
      test_s3_put:
        bucket: ops
        remote_path: chef/test_s3_put
