---
driver:
  name: ec2
  region: us-east-1
  availability_zone: us-east-1b
  instance_type: c3.large
  iam_profile_name: test-kitchen
  tags:
    Env: dev
    Type: test

provisioner:
  name: chef_zero
  client_rb:
    environment: dev

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    driver:
      tags:
        Name: s3-put-default
    run_list:
      - recipe[test_s3_put::default]
    attributes:
      test_s3_put:
        bucket: ops
        remote_path: chef/test_s3_put

  - name: default-chef12
    driver:
      tags:
        Name: s3-put-default-chef12
    provisioner:
      product_name: chef
      product_version: 12
    run_list:
      - recipe[test_s3_put::default]
    attributes:
      test_s3_put:
        bucket: ops
        remote_path: chef/test_s3_put
