language: ruby
cache:
  directories:
  - "$HOME/.berkshelf"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
if: "(type = pull_request) OR (tag IS present) OR (branch = master)"
before_install:
- eval "$(chef shell-init bash)"
- chef --version
install:
- chef gem install kitchen-sync
- berks
script: chef exec delivery local all
